version: '3.8'
services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/.:/docker-entrypoint-initdb.d/.


