version: '3.8'
services:
  api:
    build: .
    container_name: tomcat-app
    environment:
      DB_URL: jdbc:postgresql://db:5432/currency
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: currency
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/.:/docker-entrypoint-initdb.d/.


